language: rust
cache: cargo
dist: trusty
sudo: true

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

script:
- |
  cargo check &&
  cargo test &&
  cargo test --benches &&
  cargo test --release
  # cargo kcov --verbose --coveralls &&
  # bash <(curl -s https://codecov.io/bash)
