[package]
name = "modular-bitfield"
version = "0.7.0"
edition = "2018"
authors = ["Robin Freyler <robinfreyler@web.de>"]
license = "MIT/Apache-2.0"
readme = "README.md"

repository = "https://github.com/robbepop/modular-bitfield"
documentation = "https://docs.rs/modular-bitfield"
description = "Bitfields for structs that allow for modular use of enums."
categories = ["data-structures", "no-std"]
keywords   = ["bitfield", "bit", "bitfields"]

autotests = false

[dev-dependencies]
trybuild = "1.0"
criterion = "0.3"

[[test]]
name = "tests"
path = "tests/progress.rs"

[[bench]]
name = "benchmarks"
path = "benches/benchmarks.rs"
harness = false

[[bench]]
name = "cmp_handwritten"
path = "benches/cmp_handwritten.rs"
harness = false

# [[bin]]
# name = "workshop"
# path = "main.rs"

[dependencies]
modular-bitfield-impl = { path = "impl", version = "0.7" }
